[package]
name = "quick_host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
actix-files = "0.6.0"
env_logger = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
